# Generated by Django 3.2.13 on 2022-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20220703_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='selectedRepo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
